### ISSUE TITLE
Add pci support

### ISSUE THREAD

**Issue by neochapay** [5victor/linux-tiny210v2#1]
On my Tiny210v2 i have miniPCIe slot can you add him support on you kernel ?

**Comment by 5victor** [comment]
那个minipcie接口其实就是usb和pcie接口。友善之臂就用了其中的USB接口，所以，你找个这个设备的usb驱动应该就能用了。

**Comment by 5victor** [comment]
Sorry, I think you are chinese. The minipice interface contian pcie interface and usb interace. But the slot on tiny210v2 only use usb interface, so you can find a usb driver for you device, it may work.

**Comment by neochapay** [comment]
i have ath wifi on minipcie slot but in`s not work and lipci not work too

**Comment by 5victor** [comment]
the minipcie on tiny210 like a usb solt, you can find a usb driver fit you device.

**Comment by neochapay** [comment]
I have Wifi Atheros AR5BXB63 minipcie module and if i say lsub i get:
root@tiny210v2:~# lsusb 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

and lsoci get:
root@tiny210v2:~# lspci 
pcilib: Cannot open /proc/bus/pci
lspci: Cannot find any working access method.

And of course my wifi module not work :(

I can not run it?

**Comment by 5victor** [comment]
![minipcie](https://f.cloud.github.com/assets/595016/320806/ba2d823a-996a-11e2-89a8-0590f27fbed1.png)
so, you can see the minipcie equal a usb interface.

**Comment by neochapay** [comment]
Yes i see... i think maybe add wifi module but only gsm modem... sorry...
